// export const PLANT_API_SECRET_KEY = "sk-uh6a65be46fbb8b734018"
// export const PLANT_API_SECRET_KEY = "sk-FuPQ65bf46717b1154018"
// export const PLANT_API = "https://perenual.com/api/species-list?key="
export const PLANT_API = "https://trefle.io/api/v1/plants?token="
export const PLANT_API_TOKEN = "pkX14xYsMAJcqShttRutJeW5PIjrgjpVh1pGPG30Wxw"
